name: catastrophe_visualizer
description: "Advanced Disaster Visualizer with Complete Liquid Galaxy integration"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core dependencies
  dartssh2: ^2.9.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.15
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.19.0

  # Enhanced LG features
  url_launcher: ^6.1.12
  package_info_plus: ^4.0.2
  device_info_plus: ^9.1.0
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0

  # SIMPLIFIED FILE HANDLING (mobile-focused, no desktop issues)
  # Removed file_picker to avoid desktop platform issues
  # Using only path_provider + permission_handler for KML downloads

  # File handling and permissions
  permission_handler: ^11.0.1

  # UI enhancements
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0

  # SVG support
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


