name: catastrophe_visualizer
description: "Real-time disaster monitoring application for Liquid Galaxy - GSOC 2025"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.0.5

  # Networking
  http: ^1.1.0

  # XML Processing for KML
  xml: ^6.3.0

  # Date/Time utilities
  intl: ^0.18.1

  # Local Storage
  shared_preferences: ^2.2.2

  # SSH for Liquid Galaxy (add later when ready)
  # dartssh2: ^2.8.6

  # Location services (add when ready for maps)
  # geolocator: ^10.1.0
  # permission_handler: ^11.0.1
  # google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true